name: catcher
description: Plugin for error catching which provides multiple handlers for dealing with errors when they are not caught by the developer.
version: 0.7.0
homepage: https://github.com/jhomlala/catcher

environment:
   sdk: '>=2.18.2 <3.0.0'
   flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^8.1.1
  device_info_plus: ^8.0.0
  device_info_plus_platform_interface: ^7.0.0
  package_info_plus: ^3.0.1
  android_id: ^0.1.3
  package_info_plus_web: ^2.0.0
  mailer: ^5.2.0
  dio: ^4.0.1
  flutter_mailer: ^2.0.0
  logging: ^1.1.0
  sentry: ^6.13.1
  universal_io: ^2.0.4

dev_dependencies:
  lint: ^1.7.2

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.catcher
        pluginClass: CatcherPlugin
      ios:
        pluginClass: CatcherPlugin
      web:
        pluginClass: CatcherWebPlugin
        fileName: catcher_web_plugin.dart
      macos:
        pluginClass: CatcherPlugin
      windows:
        pluginClass: CatcherPlugin
      linux:
        pluginClass: CatcherPlugin
